### ISSUE TITLE
Random Map Survival stuck on Winter 2022 - 01

### ISSUE THREAD

**Issue by chreden** [GreepTheSheep/openplanet-mx-random#47]
I was playing RMS and the 4th map was Winter 2022 - 01 which I already have AT on. I did a few runs as normal and thought I was too slow, but then noticed that the time on the RMS was no longer going down.

Here's what I noticed:
- Timer was no longer counting
- I could press start/pause and it was adding 3 minutes each time, but not resuming the timer or going to the next map.
- Skip button was gone (free skip was still there)

Here's the unusual run summary after I finished:
![image](https://user-images.githubusercontent.com/4263940/153316683-17ac7c20-7c1f-4ff5-afaf-d6095c7f5b3d.png)

If it it helps it's possible that I played Winter 2022 - 01 in the same session before starting RMS, though I can't be sure about that.

**Comment by GreepTheSheep** [comment]
Added this error if that happens
![image](https://user-images.githubusercontent.com/42576124/154978126-7089ac48-25e9-4b0d-9780-975ad30822c7.png)

The reason is we add a verification on our latest maps if it corresponds on our current map, if not, the timer is paused.
Happened on Wirtual's stream some time ago (#32). This prevent having wrong map name on our timer
